C     ===== HILBERT MAIN PROGRAM =====
C
C     INVERT A 5-BY-5 HILBERT MATRIX AND THEN INVERT THE INVERSE.
C
C     TEST SUBROUTINES THAT SOLVE SYSTEMS OF LINEAR EQUATIONS
C     USING LU DECOMPOSITION (WITHOUT ITERATIVE IMPROVEMENT).
C
C     AN EXAMPLE FORTRAN IV PROGRAM WRITTEN BY RON MAK FOR CS 152.
C     REFERENCE: COMPUTER SOLUTION OF LINEAR ALGEBRAIC SYSTEMS
C                BY GEORGE FORSYTHE AND CLEVE B. MOLER
C
      DOUBLE PRECISION A, B, C, X, Y, DIS, X1R, X2R, X1I, X2I
      INTEGER COUNT
C      
      COUNT = 0
C
      READ (5,100) A, B, C
  100 FORMAT (3F10.0)
      X = -B / (2 * A)
      DIS = (B * B) - (4 * A * C)
      Y = DSQRT(DIS)
      IF (DIS .EQ. 0.0) GO TO 200
      GO TO 300
  200 X1R = X
      X2R = X
      COUNT = COUNT + 1
  300 IF(DIS .GE. 0.0) GO TO 400
      GO TO 500
  400 X1R = X + Y
      X2R = X - Y
      X1I = 0
      X2I = 0
      COUNT = COUNT + 1
      GO TO 600
  500 X1R = X
      X2R = X
      X1I = DSQRT(-DIS) / (2 * A)
      X2I = -X1I
      COUNT = COUNT + 1
  600 WRITE (6, 700) A, B, C, X1R, X2R, X1I, X2I
  700 FORMAT (1PE15.4)
C
      RETURN
      END
